
development:
  adapter: postgresql
  encoding: utf8
  database: db/development.pg
  host: localhost
  pool: 5
  username: first_app
  password:
  
test:
  adapter: postgresql
  encoding: utf8
  database: db/test.pg
  host: localhost
  pool: 5
  username: first_app
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: db/production.pg
  pool: 5
  username: first_app
  password:
